"""add likes to db

Revision ID: bd4b022527ca
Revises: 29c085c959aa
Create Date: 2023-04-18 12:00:12.611452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4b022527ca'
down_revision = '29c085c959aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
